language: python
python:
  - "2.7"

install:
  - cd ..
  - wget https://www.renpy.org/dl/8.0.3/renpy-8.0.3-sdk.tar.bz2
  - tar xf renpy-8.0.3-sdk.tar.bz2
  - rm renpy-8.0.3-sdk.tar.bz2
  - mv renpy-8.0.3-sdk renpy
  - cd renpy

script: ./renpy.sh "../game/" lint && ./renpy.sh launcher distribute "../ganbatte/"